version: '3.6'

services:
    web:
        container_name: myapp_web
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./src:/myapp
            - './build/nginx/server.conf:/etc/nginx/conf.d/default.conf'
    php:
        build:
            context: .
            dockerfile: ./build/php/Dockerfile
        container_name: myapp_php
        volumes:
            - ./src:/myapp

    db:
        image: mariadb:10.2
        container_name: myapp_db
        environment:
            - MYSQL_DATABASE=myapp
            - MYSQL_USER=myapp
            - MYSQL_PASSWORD=secret
            - MYSQL_RANDOM_ROOT_PASSWORD=1
