version: '3.6'

services:
    web:
        container_name: myapp_web
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - .:/var/www
            - './build/nginx/server.conf:/etc/nginx/conf.d/default.conf'
