version: '3.6'

services:
    web:
        container_name: myapp_web
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./src:/myapp
            - './build/nginx/server.conf:/etc/nginx/conf.d/default.conf'
    php:
        build:
            context: .
            dockerfile: ./build/php/Dockerfile
        container_name: myapp_php
        volumes:
            - ./src:/myapp
